#Docker compose file links mongoDB and flask app.
web:
  build: .
  environment:
    - TZ=America/New_York
    - DEBIAN_FRONTEND=noninteractive
  ports:
    - "5000:5000"
  volumes:
      - .:/app
  links:
    - db
db:
  image: mongo:3.0.2
